/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package componenteteorico13;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class VentanaDatos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDatos
     */
    public VentanaDatos() {
        initComponents();
        
        // GENERAR TABLA CON FILAS Y COLUMNAS
        // Definir las columnas de la tabla
        String[] columnas = { "Nombre", "Apellido", "Edad" };
        Object[][] datosTabla = {
            { "Walter", "White", 50 },
            { "Jesse", "Pinkman", 24 },
            { "Saul", "Goodman", 40 }
        };
        
        DefaultTableModel modeloTabla = new DefaultTableModel(datosTabla, columnas);
        
        // Asignar el modelo a la tabla
        tablaValores.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaMeses = new javax.swing.JList<>();
        txtResultado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaValores = new javax.swing.JTable();
        btnAddColumna = new javax.swing.JButton();
        btnAddFila = new javax.swing.JButton();
        btnDeleteColumna = new javax.swing.JButton();
        btnDeleteFila = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaMeses.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaMeses.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaMesesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaMeses);

        txtResultado.setText("jTextField1");

        jScrollPane2.setViewportView(tablaValores);

        btnAddColumna.setText("Agregar Columna");
        btnAddColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddColumnaActionPerformed(evt);
            }
        });

        btnAddFila.setText("Agregar Fila");
        btnAddFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFilaActionPerformed(evt);
            }
        });

        btnDeleteColumna.setText("Eliminar Columna");
        btnDeleteColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteColumnaActionPerformed(evt);
            }
        });

        btnDeleteFila.setText("Eliminar Fila");
        btnDeleteFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddFila, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteFila, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddColumna)
                    .addComponent(btnAddFila)
                    .addComponent(btnDeleteColumna)
                    .addComponent(btnDeleteFila))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaMesesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaMesesValueChanged
        // TODO add your handling code here:
        // getSelectedIndex() -- posicion del elemento seleccionado
        // getSelectedIndices() -- posiciones de los elementos seleccionados
        // getSelectedValue() -- el valor del elemento seleccionado
        // getSelectedValuesList() -- una lista con los valores de los elementos seleccionados
        txtResultado.setText("El mes seleccionado es: " + listaMeses.getSelectedValue());
    }//GEN-LAST:event_listaMesesValueChanged

    private void btnAddColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddColumnaActionPerformed
        // TODO add your handling code here:
        
        // Obtener el modelo de la tabla
        DefaultTableModel modeloTabla = (DefaultTableModel)tablaValores.getModel();
        String[] generos = { "M", "M", "M" };
        modeloTabla.addColumn("Género", generos);
        
        // Actualizar la tabla
        tablaValores.setModel(modeloTabla);
    }//GEN-LAST:event_btnAddColumnaActionPerformed

    private void btnAddFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFilaActionPerformed
        // TODO add your handling code here:
        // Obtener el modelo de la tabla
        DefaultTableModel modeloTabla = (DefaultTableModel)tablaValores.getModel();
        Object[] nuevaFila = { "Jane", "Doe", 25, "F"};
        modeloTabla.addRow(nuevaFila);
        
        // Actualizar la tabla
        tablaValores.setModel(modeloTabla);
    }//GEN-LAST:event_btnAddFilaActionPerformed

    private void btnDeleteColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteColumnaActionPerformed
        // TODO add your handling code here:
        // Eliminar la ultima columna de la tabla
        // Obtener el modelo de la tabla
        DefaultTableModel modeloTabla = (DefaultTableModel)tablaValores.getModel();
        int cantidadColumnas = modeloTabla.getColumnCount();
        modeloTabla.setColumnCount(cantidadColumnas - 1);
        // Actualizar Tabla
        tablaValores.setModel(modeloTabla);
    }//GEN-LAST:event_btnDeleteColumnaActionPerformed

    private void btnDeleteFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFilaActionPerformed
        // TODO add your handling code here:
        // Obtener el modelo de la tabla
        DefaultTableModel modeloTabla = (DefaultTableModel)tablaValores.getModel();
        int cantidadFilas = modeloTabla.getRowCount();
        // Eliminar ultima fila de la tabla
        modeloTabla.removeRow(cantidadFilas - 1);
        // Actualizar modelo
        tablaValores.setModel(modeloTabla);
    }//GEN-LAST:event_btnDeleteFilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddColumna;
    private javax.swing.JButton btnAddFila;
    private javax.swing.JButton btnDeleteColumna;
    private javax.swing.JButton btnDeleteFila;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaMeses;
    private javax.swing.JTable tablaValores;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
